-- Seed data for public.incubators.
-- Populated manually (no automated ingestion pipeline exists yet — see
-- /areas/aza.md notes on the opportunities content-ops gap for the planned fix).
-- logo_url uses Clearbit's public logo endpoint (https://logo.clearbit.com/{domain}),
-- which resolves live at runtime rather than hosting assets in Supabase Storage.
-- Trade-off: depends on the org's domain/favicon staying live and on Clearbit's
-- endpoint remaining available without a key. If permanence is required, re-host
-- these in Supabase Storage instead.

insert into public.incubators (name, description, focus_area, location, remote, application_url, logo_url, curator_verified) values
('Co-Creation Hub (CcHub)', 'Nigeria''s first innovation hub, offering a 6-month pre-incubation program with $5,000 funding, 12-month incubation with $25,000, and a 12-week accelerator offering up to $250,000.', 'Tech, social impact', 'Lagos, Abuja', false, 'https://cchubnigeria.com', 'https://logo.clearbit.com/cchubnigeria.com', true),
('Tony Elumelu Foundation Entrepreneurship Programme', 'Pan-African programme for entrepreneurs across all 54 countries with businesses not older than five years. Provides $5,000 non-refundable seed capital, 12 weeks of business training, and mentorship.', 'All sectors, pan-African', 'Pan-African', true, 'https://www.tefconnect.com', 'https://logo.clearbit.com/tonyelumelufoundation.org', true),
('Wennovation Hub', 'Pioneer Nigerian innovation accelerator focused on social impact sectors: agriculture, healthcare, education, clean energy, and infrastructure.', 'Social impact, agritech, healthtech', 'Lagos', false, 'https://wennovation.com', 'https://logo.clearbit.com/wennovation.com', true),
('Fast Forward Venture Studio and Fund', 'Venture studio and early-stage fund with a mission to unlock prosperity in Africa through innovative solutions.', 'Pre-seed, seed', 'Lagos', false, null, 'https://logo.clearbit.com/fastforwardvc.com', false),
('Itanna', 'Honeywell Group''s innovation accelerator investing in promising tech-enabled startups across Nigeria and Africa. Four-month program with initial funding and hands-on advice.', 'Tech-enabled startups', 'Lagos', false, null, 'https://logo.clearbit.com/itanna.vc', false),
('Cascador', 'Supports mid-stage, mission-driven entrepreneurs across Africa with a six-month program and personalized mentorship from American and Nigerian business leaders.', 'Mission-driven, growth capital', 'Africa-wide', true, null, 'https://logo.clearbit.com/cascadorafrica.org', false),
('GreenHouse Capital (GIBE)', 'Runs multiple accelerator programs each year to empower budding entrepreneurs across Africa.', 'Fintech, early-stage', 'Lagos', false, null, 'https://logo.clearbit.com/greenhousecapital.co', false),
('FasterCapital', 'Offers a Tech Cofounder program covering 50% of development costs, and a Raise Capital program connecting startups with investors.', 'Tech cofounder, fundraising support', 'Global', true, 'https://fastercapital.com', 'https://logo.clearbit.com/fastercapital.com', false),
('Enspire Incubator', 'Three-month incubation program with training and mentoring for startups with a basic product, connecting them with potential investors.', 'Early-stage, investor connections', 'Lagos', false, null, 'https://logo.clearbit.com/enspireincubator.com', false),
('Labs by ARM', 'Leading startup incubator in Nigeria by portfolio count, supporting early-stage ventures.', 'Early-stage', 'Lagos', false, null, 'https://logo.clearbit.com/labsbyarm.com', false),
('Founder Institute', 'World''s largest pre-seed startup accelerator, with chapters across 200+ cities and 95+ countries. Evaluates founders via an Entrepreneur DNA Assessment rather than requiring a product.', 'Idea to pre-seed, all sectors', 'Global — 200+ cities', true, 'https://fi.co/apply', 'https://logo.clearbit.com/fi.co', false),
('Techstars Anywhere', 'Remote-first Techstars accelerator delivering the same mentorship, funding, and network as in-person programs, with three mandatory in-person offsites for founders in American time zones.', 'All sectors', 'Remote (Americas time zones)', true, 'https://www.techstars.com/accelerators/anywhere', 'https://logo.clearbit.com/techstars.com', false),
('Y Combinator', 'The world''s most recognized accelerator. Standard deal is $500k for a SAFE, three months in-person in San Francisco with weekly dinners and office hours. Open to founders from anywhere, including Africa.', 'All sectors', 'San Francisco', false, 'https://www.ycombinator.com/apply', 'https://logo.clearbit.com/ycombinator.com', true),
('500 Global', 'Flagship accelerator with a four-month program; roughly 30-40% of each cohort is international, reflecting its global, emerging-markets focus.', 'Early-stage tech, global', 'Palo Alto (global reach)', true, 'https://500.co', 'https://logo.clearbit.com/500.co', false),
('Antler', 'Day-zero global investor and co-founder matching program, active in 30+ cities. Six-week FORM residency followed by a post-investment LAUNCH phase.', 'Industry-agnostic, co-founder matching', 'Global — 30+ cities', true, 'https://www.antler.co/apply', 'https://logo.clearbit.com/antler.co', false),
('Entrepreneur First', 'Talent investor that funds individuals before they have a co-founder or idea. Two 12-week sprints: FORM (team + idea) and LAUNCH (fundraising).', 'Deep tech, solo founders', 'London, Paris, Bangalore, NYC', false, 'https://apply.joinef.com', 'https://logo.clearbit.com/joinef.com', false),
('MassChallenge', 'Equity-free accelerator; funding comes through prizes, awards, and partner-backed support rather than equity stakes. Strong mentorship and partner exposure across healthcare, fintech, climate, and cybersecurity tracks.', 'No-equity, multi-sector', 'Boston, Switzerland, Israel, Texas', false, 'https://masschallenge.org', 'https://logo.clearbit.com/masschallenge.org', false),
('Village Capital', 'Impact-focused accelerator and investment firm known for peer-selected funding, where founders in each cohort vote on which companies receive investment.', 'Impact, peer-selected funding', 'Global', true, 'https://vilcap.com', 'https://logo.clearbit.com/vilcap.com', false),
('Seedcamp', 'Europe''s first accelerator, offering a year-long support platform rather than a fixed cohort sprint. Focus on founders with global ambition.', 'Early-stage, Europe-focused', 'London', false, 'https://seedcamp.com', 'https://logo.clearbit.com/seedcamp.com', false),
('Google for Startups Accelerator', 'Equity-free accelerator offering up to $100k in cloud credits and mentorship, with regional tracks including AI, Climate, Africa, and Women Founders.', 'No-equity, AI, climate, Africa, women founders', 'Global (regional cohorts)', true, 'https://startup.google.com/accelerator', 'https://logo.clearbit.com/startup.google.com', false),
('Plug and Play Tech Center', 'Zero-equity accelerator and innovation platform with 60+ global locations, connecting startups with corporate partners across many industries.', 'No-equity, corporate innovation', 'Silicon Valley (60+ global locations)', true, 'https://www.plugandplaytechcenter.com', 'https://logo.clearbit.com/plugandplaytechcenter.com', false),
('Alchemist Accelerator', 'Focused on B2B and enterprise startups selling to large companies, with a corporate buyer network that helps convert pilots to revenue faster.', 'Enterprise B2B', 'San Francisco', false, 'https://alchemistaccelerator.com', 'https://logo.clearbit.com/alchemistaccelerator.com', false),
('AngelPad', 'Highly selective 10-week intensive with fewer than 15 teams per batch and under 1% acceptance rate. Strong emphasis on team strength and hard metrics.', 'All sectors, highly selective', 'NYC, San Francisco', false, 'https://angelpad.org', 'https://logo.clearbit.com/angelpad.org', false),
('Startupbootcamp', 'Deep vertical specialization, running dedicated regional and industry-specific programs. Three-month intensive with 100+ mentors per cohort.', 'Vertical-specific (fintech, energy, etc.)', 'Global — 20+ countries', false, 'https://startupbootcamp.org', 'https://logo.clearbit.com/startupbootcamp.org', false),
('SOSV', 'Umbrella of specialized accelerators including HAX (hardware/robotics/climate) and IndieBio (biotech/climate/food), each with deep sector focus and lab/manufacturing access.', 'Deep tech, biotech, hardware', 'Multiple (Newark, SF/NYC, Shenzhen)', false, 'https://sosv.com', 'https://logo.clearbit.com/sosv.com', false),
('Creative Destruction Lab (CDL)', 'Nonprofit, no-equity, objectives-based program for seed-stage, science-based companies. Global network with 16 locations and streams in AI, health, climate, quantum computing, and space.', 'Science-based, deep tech, no-equity', 'Global — 16 sites (Canada, US, Europe, Australia, Middle East)', false, 'https://creativedestructionlab.com', 'https://logo.clearbit.com/creativedestructionlab.com', false),
('1752vc (Accelerate)', 'Remote-first accelerator (formerly Pegasus Angel Accelerator) investing $100k with a valuation cap of up to $3.5M. Rolling admissions with no fixed start dates, focused on go-to-market and sales training.', 'Go-to-market, sales, remote-first', 'Remote-first (Southern California)', true, 'https://www.1752.vc/accelerate', 'https://logo.clearbit.com/1752.vc', false)
on conflict do nothing;
